services:
  ahorro-service:
    build:
      context: ./Ahorro-service  # Ruta al Dockerfile del servicio de ahorro
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - MONGO_URL=mongodb://mongo:27017/save-service-db
    depends_on:
      - mongo
    restart: always

  user-service:
    build:
      context: ./user-service  # Ruta al Dockerfile del servicio de usuarios
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/user-service-db
    depends_on:
      - mongo
    restart: always

  gastos-service:
    build: 
      context: ./expenses-service  # Ruta al Dockerfile del servicio de usuarios
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=gastos_db
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gastos_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
    driver: local
